apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  labels:
    app: backend-rest-app
    tier: backend

spec:
  # type: Cluster IP is a default service
  selector:
    app: backend-rest-app
  ports:
    - name: http
      port: 8080 # Cluster IP service Port
      targetPort: 8080