apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx-app-nodeport-service
  labels:
    app: frontend-nginx-app
    tier: frontend
spec:
  type: NodePort
  selector:
    app: frontend-nginx-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31234