apiVersion: v1
kind: service
metadata:
  name: myapp-pod-nodeport-service
  labels:
    app: myapp
spec:
  type: NodePort
  selector:
  # LoadBalance traffic across Pods matching this label selector
    app: myapp
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31231