apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp2-rs
spec:
  replicas: 3
  selector:
    matchLabels:
  template:
    metadata:
      name: myapp2-pod
      labels:
        app: myapp2
        tier: frontend
    spec:
      containers:
        - name: myapp2-container
          image: stacksimplify/kubenginx:2.0.0
          ports: 
            - containerPort: 80